version: '2'

services:

  lamp:
    build:
      context: .
      dockerfile: Dockerfile
    image: alexcheng/apache2-php7
    container_name: lamp
    stdin_open: true
    tty: true
    restart: unless-stopped
    expose:
      - '80'
      - '443'
    environment:
      - HOSTNAME=lamp
    volumes:
      - app_data_lamp:/var/www/html
      - ./dev:/var/www/ecarddesign
      - ./etc/apache2/sites-enabled:/etc/apache2/sites-enabled/:ro
    networks:
      default:
        ipv4_address: 172.25.0.11
    links:
      - mysql


  mysql:
    image: mysql
    container_name: mysql
    expose:
      - '3306'
    environment:
      - HOSTNAME=mysql
      - MYSQL_ROOT_PASSWORD=.3c4rd.
      - MYSQL_USER=ecarddesign
      - MYSQL_PASSWORD=.3c4rd.
      - MYSQL_DATABASE=ecarddesign
    volumes: 
      - ./etc/mysql:/docker-entrypoint-initdb.d
      - ./var/lib/mysql:/var/lib/mysql:rw
    networks:
      default:
        ipv4_address: 172.25.0.12


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  172.25.0.0/16

volumes:
  app_data_lamp:
