BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "usuarios" (
	"id"	INTEGER NOT NULL UNIQUE,
	"nombres"	TEXT NOT NULL,
	"apellidos"	TEXT NOT NULL,
	"correo"	TEXT NOT NULL UNIQUE,
	"usuario"	TEXT NOT NULL UNIQUE,
	"clave"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
